name: Arlo Downloader
version: "1.0.0"
slug: arlo-downloader
description: Download Arlo camera recordings to network storage for long-term archival
url: https://github.com/diaznet/arlo-downloader
arch:
  - aarch64
  - amd64
  - armv7

startup: services
boot: auto
init: false

map:
  - media:rw

options:
  arlo_username: ""
  arlo_password: ""
  media_folder: ""
  tfa_type: PUSH
  tfa_source: push
  tfa_retries: 10
  tfa_delay: 5
  debug: false

schema:
  arlo_username: str
  arlo_password: password
  media_folder: str
  tfa_type: "list(PUSH|EMAIL)"
  tfa_source: "list(push|imap)"
  tfa_retries: "int(1,30)"
  tfa_delay: "int(1,60)"
  tfa_host: "str?"
  tfa_username: "str?"
  tfa_password: "password?"
  debug: bool
